"""
Controller and Baseband HCI Commands

This module provides classes for Controller and Baseband HCI commands.
"""

import struct
from typing import List, Dict, Any, ClassVar, Optional, Tuple, Union
from enum import IntEnum

from ..cmd_base_packet import HciCmdBasePacket
from ..cmd_opcodes import HciOpcode, create_opcode, OGF, ControllerBasebandOCF
from .. import register_command

class Reset(HciCmdBasePacket):
    """Reset Command"""
    
    OPCODE = HciOpcode.RESET
    NAME = "Reset"
    
    def __init__(self):
        """Initialize Reset Command (no parameters)"""
        super().__init__()
    
    def _validate_params(self) -> None:
        """Validate command parameters (none for Reset)"""
        pass
    
    def _serialize_params(self) -> bytes:
        """Serialize parameters to bytes (no parameters)"""
        return b''
    
    @classmethod
    def from_bytes(cls, data: bytes) -> 'Reset':
        """Create command from parameter bytes (excluding header)"""
        return cls()

class SetEventMask(HciCmdBasePacket):
    """Set Event Mask Command"""
    
    OPCODE = HciOpcode.SET_EVENT_MASK
    NAME = "Set_Event_Mask"
    
    def __init__(self, event_mask: int = 0x00001FFFFFFFFFFF):
        """
        Initialize Set Event Mask Command
        
        Args:
            event_mask: 8-byte bitmask that controls which events are generated by the controller
                        Default: All events except reserved bits
        """
        super().__init__(event_mask=event_mask)
    
    def _validate_params(self) -> None:
        """Validate command parameters"""
        if not (0 <= self.params['event_mask'] <= 0xFFFFFFFFFFFFFFFF):
            raise ValueError(f"Invalid event_mask: {self.params['event_mask']}, must be an 8-byte value")
    
    def _serialize_params(self) -> bytes:
        """Serialize parameters to bytes"""
        return struct.pack("<Q", self.params['event_mask'])
    
    @classmethod
    def from_bytes(cls, data: bytes) -> 'SetEventMask':
        """Create command from parameter bytes (excluding header)"""
        if len(data) < 8:
            raise ValueError(f"Invalid data length: {len(data)}, expected at least 8 bytes")
        
        event_mask = struct.unpack("<Q", data[:8])[0]
        
        return cls(event_mask=event_mask)

class WriteLocalName(HciCmdBasePacket):
    """Write Local Name Command"""
    
    OPCODE = create_opcode(OGF.CONTROLLER_BASEBAND, ControllerBasebandOCF.WRITE_LOCAL_NAME)
    NAME = "Write_Local_Name"
    
    def __init__(self, local_name: str):
        """
        Initialize Write Local Name Command
        
        Args:
            local_name: The name to set for the local device (up to 248 bytes)
        """
        # Convert string to bytes if needed
        if isinstance(local_name, str):
            local_name = local_name.encode('utf-8')
            
        super().__init__(local_name=local_name)
    
    def _validate_params(self) -> None:
        """Validate command parameters"""
        if len(self.params['local_name']) > 248:
            raise ValueError(f"Invalid local_name length: {len(self.params['local_name'])}, must be at most 248 bytes")
    
    def _serialize_params(self) -> bytes:
        """Serialize parameters to bytes"""
        # Pad name to 248 bytes
        local_name = self.params['local_name'] + b'\x00' * (248 - len(self.params['local_name']))
        return struct.pack("<248s", local_name)
    
    @classmethod
    def from_bytes(cls, data: bytes) -> 'WriteLocalName':
        """Create command from parameter bytes (excluding header)"""
        if len(data) < 248:
            raise ValueError(f"Invalid data length: {len(data)}, expected at least 248 bytes")
        
        local_name = data[:248].rstrip(b'\x00')
        
        return cls(local_name=local_name)

class ReadLocalName(HciCmdBasePacket):
    """Read Local Name Command"""
    
    OPCODE = create_opcode(OGF.CONTROLLER_BASEBAND, ControllerBasebandOCF.READ_LOCAL_NAME)
    NAME = "Read_Local_Name"
    
    def __init__(self):
        """Initialize Read Local Name Command (no parameters)"""
        super().__init__()
    
    def _validate_params(self) -> None:
        """Validate command parameters (none for Read Local Name)"""
        pass
    
    def _serialize_params(self) -> bytes:
        """Serialize parameters to bytes (no parameters)"""
        return b''
    
    @classmethod
    def from_bytes(cls, data: bytes) -> 'ReadLocalName':
        """Create command from parameter bytes (excluding header)"""
        return cls()

# Function wrappers for easier access
def reset() -> Reset:
    """Create Reset Command"""
    return Reset()

def set_event_mask(event_mask: int = 0x00001FFFFFFFFFFF) -> SetEventMask:
    """Create Set Event Mask Command"""
    return SetEventMask(event_mask=event_mask)

def write_local_name(local_name: str) -> WriteLocalName:
    """Create Write Local Name Command"""
    return WriteLocalName(local_name=local_name)

def read_local_name() -> ReadLocalName:
    """Create Read Local Name Command"""
    return ReadLocalName()

# Register all command classes
register_command(Reset)
register_command(SetEventMask)
register_command(WriteLocalName)
register_command(ReadLocalName)

# Export public functions and classes
__all__ = [
    'reset',
    'set_event_mask',
    'write_local_name',
    'read_local_name',
    'Reset',
    'SetEventMask',
    'WriteLocalName',
    'ReadLocalName',
]