"""
    Defines opcodes for HCI commands
"""
from enum import IntEnum

# OGF (OpCode Group Field) definitions
class OGF(IntEnum):
    LINK_CONTROL = 0x01
    LINK_POLICY = 0x02
    CONTROLLER_BASEBAND = 0x03
    INFORMATION_PARAMS = 0x04
    STATUS_PARAMS = 0x05
    TESTING = 0x06
    LE_CONTROLLER = 0x08
    VENDOR_SPECIFIC = 0x3F

# OCF (OpCode Command Field) definitions for each OGF

# Link Control Commands (OGF = 0x01)
class LinkControlOCF(IntEnum):
    INQUIRY = 0x0001
    INQUIRY_CANCEL = 0x0002
    PERIODIC_INQUIRY_MODE = 0x0003
    EXIT_PERIODIC_INQUIRY_MODE = 0x0004
    CREATE_CONNECTION = 0x0005
    DISCONNECT = 0x0006
    CREATE_CONNECTION_CANCEL = 0x0008
    ACCEPT_CONNECTION_REQUEST = 0x0009
    REJECT_CONNECTION_REQUEST = 0x000A
    LINK_KEY_REQUEST_REPLY = 0x000B
    LINK_KEY_REQUEST_NEGATIVE_REPLY = 0x000C
    PIN_CODE_REQUEST_REPLY = 0x000D
    PIN_CODE_REQUEST_NEGATIVE_REPLY = 0x000E
    CHANGE_CONNECTION_PACKET_TYPE = 0x000F
    AUTHENTICATION_REQUESTED = 0x0011
    SET_CONNECTION_ENCRYPTION = 0x0013
    CHANGE_CONNECTION_LINK_KEY = 0x0015
    MASTER_LINK_KEY = 0x0017
    REMOTE_NAME_REQUEST = 0x0019
    REMOTE_NAME_REQUEST_CANCEL = 0x001A
    READ_REMOTE_SUPPORTED_FEATURES = 0x001B
    READ_REMOTE_EXTENDED_FEATURES = 0x001C
    READ_REMOTE_VERSION_INFORMATION = 0x001D
    READ_CLOCK_OFFSET = 0x001F
    READ_LMP_HANDLE = 0x0020
    SETUP_SYNCHRONOUS_CONNECTION = 0x0028
    ACCEPT_SYNCHRONOUS_CONNECTION_REQUEST = 0x0029
    REJECT_SYNCHRONOUS_CONNECTION_REQUEST = 0x002A
    IO_CAPABILITY_REQUEST_REPLY = 0x002B
    USER_CONFIRMATION_REQUEST_REPLY = 0x002C
    USER_CONFIRMATION_REQUEST_NEGATIVE_REPLY = 0x002D
    USER_PASSKEY_REQUEST_REPLY = 0x002E
    USER_PASSKEY_REQUEST_NEGATIVE_REPLY = 0x002F
    REMOTE_OOB_DATA_REQUEST_REPLY = 0x0030
    REMOTE_OOB_DATA_REQUEST_NEGATIVE_REPLY = 0x0033
    IO_CAPABILITY_REQUEST_NEGATIVE_REPLY = 0x0034
    ENHANCED_SETUP_SYNCHRONOUS_CONNECTION = 0x003D
    ENHANCED_ACCEPT_SYNCHRONOUS_CONNECTION = 0x003E
    TRUNCATED_PAGE_MODE = 0x003F
    TRUNCATED_PAGE_MODE_CANCEL = 0x0040
    SET_CONNECTIONLESS_PERIPHERAL_BROADCAST = 0x0041
    SET_CONNECTIONLESS_PERIPHERAL_BROADCAST_RECIEVE = 0x0042
    START_SYNCHRNONIZATION_TRAIN = 0x0043
    READ_SYNCHRONIZATION_TRAIN = 0x0044
    REMOTE_OOB_EXTENDED_DATA_REQUEST_REPLY = 0x0045
    
# Link Policy Commands (OGF = 0x02)
class LinkPolicyOCF(IntEnum):
    HOLD_MODE = 0x0001
    SNIFF_MODE = 0x0003
    EXIT_SNIFF_MODE = 0x0004
    QOS_SETUP = 0x0007
    ROLE_DISCOVERY = 0x0009
    SWITCH_ROLE = 0x000B
    READ_LINK_POLICY_SETTINGS = 0x000C
    WRITE_LINK_POLICY_SETTINGS = 0x000D
    READ_DEFAULT_LINK_POLICY_SETTINGS = 0x000E
    WRITE_DEFAULT_LINK_POLICY_SETTINGS = 0x000F
    FLOW_SPECIFICATION = 0x0010
    SNIFF_SUBRATING = 0x0011
    
# Controller & Baseband Commands (OGF = 0x03)
class ControllerBasebandOCF(IntEnum):
    SET_EVENT_MASK = 0x0001
    RESET = 0x0003
    SET_EVENT_FILTER = 0x0005
    FLUSH = 0x0008
    READ_PIN_TYPE = 0x0009
    WRITE_PIN_TYPE = 0x000A
    READ_STORED_LINK_KEY = 0x000D
    WRITE_STORED_LINK_KEY = 0x0011
    DELETE_STORED_LINK_KEY = 0x0012
    WRITE_LOCAL_NAME = 0x0013
    READ_LOCAL_NAME = 0x0014
    READ_CONNECTION_ACCEPT_TIMEOUT = 0x0015
    WRITE_CONNECTION_ACCEPT_TIMEOUT = 0x0016
    READ_PAGE_TIMEOUT = 0x0017
    WRITE_PAGE_TIMEOUT = 0x0018
    READ_SCAN_ENABLE = 0x0019
    WRITE_SCAN_ENABLE = 0x001A
    READ_PAGE_SCAN_ACTIVITY = 0x001B
    WRITE_PAGE_SCAN_ACTIVITY = 0x001C
    READ_INQUIRY_SCAN_ACTIVITY = 0x001D
    WRITE_INQUIRY_SCAN_ACTIVITY = 0x001E
    READ_AUTHENTICATE_ENABLE = 0x001F
    WRITE_AUTHENTICATE_ENABLE = 0x0020
    READ_CLASS_OF_DEVICE = 0x0023
    WRITE_CLASS_OF_DEVICE = 0x0024
    READ_VOICE_SETTING = 0x0025
    WRITE_VOICE_SETTING = 0x0026
    READ_AUTO_FLUSH_TIMEOUT = 0x0027
    WRITE_AUTO_FLUSH_TIMEOUT = 0x0028
    READ_NUM_BROADCAST_RETRANSMISSIONS = 0x0029
    WRITE_NUM_BROADCAST_RETRANSMISSIONS = 0x002A
    READ_HOLD_MODE_ACTIVITY = 0x002B
    WRITE_HOLD_MODE_ACTIVITY = 0x002C
    READ_TRANSMIT_POWER_LEVEL = 0x002D
    READ_SYNC_FLOW_CONTROL_ENABLE = 0x002E
    WRITE_SYNC_FLOW_CONTROL_ENABLE = 0x002F
    SET_CONTROLLER_TO_HOST_FLOW_CONTROL = 0x0031
    HOST_BUFFER_SIZE = 0x0033
    HOST_NUMBER_OF_COMPLETED_PACKETS = 0x0035
    READ_LINK_SUPERVISION_TIMEOUT = 0x0036
    WRITE_LINK_SUPERVISION_TIMEOUT = 0x0037
    READ_NUMBER_OF_SUPPORTED_IAC = 0x0038
    READ_CURRENT_IAC_LAP = 0x0039
    WRITE_CURRENT_IAC_LAP = 0x003A
    SET_AFH_HOST_CHANNEL_CLASSIFICATION = 0x003F
    READ_INQUIRY_SCAN_TYPE = 0x0041
    WRITE_INQUIRY_SCAN_TYPE = 0x0042
    READ_INQUIRY_MODE = 0x0043
    WRITE_INQUIRY_MODE = 0x0044
    READ_PAGE_SCAN_TYPE = 0x0045
    WRITE_PAGE_SCAN_TYPE = 0x0046
    READ_PAGE_SCAN_TYPE = 0x0047
    WRITE_PAGE_SCAN_TYPE = 0x0048
    READ_AFH_CHANNEL_ASSESSMENT_MODE = 0x0049
    WRITE_AFH_CHANNEL_ASSESSMENT_MODE = 0x004A
    READ_EXTENDED_INQUIRY_RESPONSE = 0x004B
    WRITE_EXTENDED_INQUIRY_RESPONSE = 0x004C
    REFRESH_ENCRYPTION_KEY = 0x004D
    READ_SIMPLE_PAIRING_MODE = 0x0051
    WRITE_SIMPLE_PAIRING_MODE = 0x0052
    READ_LOCAL_OOB_DATA = 0x0053
    READ_INQUIRY_RESPONSE_TRANSMIT_POWER_LEVEL = 0x0054
    WRITE_INQUIRY_TRANSMIT_POWER_LEVEL = 0x0055
    SEND_KEYPRESS_NOTIFICATION = 0x0056
    READ_DEFAULT_ERREORNEOUS_DATA_REPORTING = 0x0057
    WRITE_DEFAULT_ERREORNEOUS_DATA_REPORTING = 0x0058
    ENHANCED_FLUSH = 0x0059
    SET_EVENT_MASK_PAGE_2 = 0x005A
    READ_FLOW_CONTROL_MODE = 0x005B
    WRITE_FLOW_CONTROL_MODE = 0x005C
    READ_ENHANCED_TRANSMIT_POWER_LEVEL = 0x005D
    READ_LE_HOST_SUPPORT = 0x005E
    WRITE_LE_HOST_SUPPORT = 0x005F
    SET_MWS_CHANNELS_PARAMETERS = 0x0060
    SET_EXTERNAL_FRAME_CONFIGURATION = 0x0061
    SET_MWS_SIGNALING = 0x0062
    SET_MWS_TRANSPORT_LAYER = 0x0063
    SET_MWS_SCAN_FREQUENCY_TABLE = 0x0064
    SET_MWS_PATTERN_CONFIGURATION = 0x0065
    SET_RESERVED_LT_ADDR = 0x0066
    DELETE_RESERVED_LT_ADDR = 0x0067
    SET_CONNNECTIONLESS_PERIPHERAL_BROADCAST_DATA = 0x0068
    READ_SYNC_TRAIN_PARAMETERS = 0x0069
    WRITE_SYNC_TRAIN_PARAMETERS = 0x006A
    READ_SECURE_CONNECTIONS_HOST_SUPPORT = 0x006B
    WRITE_SECURE_CONNECTIONS_HOST_SUPPORT = 0x006C
    READ_AUTHETICATED_PAYLOAD_TIMEOUT = 0x0071
    WRITE_AUTHENTICATED_PAYLOAD_TIMEOUT = 0x0072
    READ_LOCAL_OOB_EXTENDED_DATA = 0x0073
    READ_EXTERNAL_PAGE_TIMEOUT = 0x0074
    WRITE_EXTERNAL_PAGE_TIMEOUT = 0x0075
    READ_EXTENDED_INQUIRY_LENGTH = 0x0076
    WRITE_EXTENDED_INQUIRY_LENGTH = 0x0077
    SET_ECOSYSTEM_BASE_INTERVAL = 0x0078
    CONFIGURE_DATA_PATH = 0x0079
    SET_MIN_ENCRYPTION_KEY_SIZE = 0x007A
    READ_MIN_ENCRYPTION_KEY_SIZE = 0x007B

# Information Parameters Commands (OGF = 0x04)
class InformationOCF(IntEnum):
    READ_LOCAL_VERSION_INFORMATION = 0x0001
    READ_LOCAL_SUPPORTED_COMMANDS = 0x0002
    READ_LOCAL_SUPPORTED_FEATURES = 0x0003
    READ_LOCAL_EXTENDED_FEATURES = 0x0004
    READ_BUFFER_SIZE = 0x0005
    READ_BD_ADDR = 0x0009
    READ_DATA_BLOCK_SIZE = 0x000A
    READ_LOCAL_SUPPORTED_CODECS = 0x000D
    READ_LOCAL_SUPPORTED_CODECS_V2 = 0x000B
    READ_LOCAL_SIMPLE_PAIRING_OPTIONS = 0x000C
    READ_LOCAL_SUPPORTED_CODECS_CAPABILITIES = 0x000E
    READ_LOCAL_SUPPORTED_CONTROLLER_DELAY = 0x000F

# Status Parameters Commands (OGF = 0x05)
class StatusOCF(IntEnum):
    READ_FAILED_CONTACT_COUNTER = 0x0001
    RESET_FAILED_CONTACT_COUNTER = 0x0002
    READ_LINK_QUALITY = 0x0003
    READ_RSSI = 0x0005
    READ_LINK_QUALITY = 0x0003
    READ_AFH_CHANNEL_MAP = 0x0006
    READ_CLOCK = 0x0007
    READ_ENCRYPTION_KEY_SIZE = 0x0008
    GET_MWS_TRANSPORT_LAYER_CONFIGURATION = 0x0009
    SET_TRIGGERED_CLOCK_CAPTURE = 0x000A
    READ_TRIGGERED_CLOCK_CAPTURE = 0x000B
    READ_LOCAL_AMP_INFO = 0x000C
    READ_LOCAL_AMP_ASSOCIATED_CODING = 0x000D

# Testing Commands (OGF = 0x06)
class TestingOCF(IntEnum):
    READ_LOOPBACK_MODE = 0x0001
    WRITE_LOOPBACK_MODE = 0x0002
    ENABLE_DEVICE_UNDER_TEST_MODE = 0x0003
    WRITE_SIMPLE_PAIRING_DEBUG_MODE = 0x0004
    WRITE_SECURE_CONNECTIONS_TEST_MODE = 0x0005

# LE Controller Commands (OGF = 0x08)
class LEControllerOCF(IntEnum):
    SET_EVENT_MASK = 0x0001
    READ_BUFFER_SIZE = 0x0002
    READ_LOCAL_SUPPORTED_FEATURES = 0x0003
    SET_RANDOM_ADDRESS = 0x0005
    SET_ADVERTISING_PARAMETERS = 0x0006
    READ_ADVERTISING_CHANNEL_TX_POWER = 0x0007
    SET_ADVERTISING_DATA = 0x0008
    SET_SCAN_RESPONSE_DATA = 0x0009
    SET_ADVERTISE_ENABLE = 0x000A
    SET_SCAN_PARAMETERS = 0x000B
    SET_SCAN_ENABLE = 0x000C
    CREATE_CONNECTION = 0x000D
    CREATE_CONNECTION_CANCEL = 0x000E
    READ_WHITE_LIST_SIZE = 0x000F
    CLEAR_WHITE_LIST = 0x0010
    ADD_DEVICE_TO_WHITE_LIST = 0x0011
    REMOVE_DEVICE_FROM_WHITE_LIST = 0x0012
    CONNECTION_UPDATE = 0x0013
    SET_HOST_CHANNEL_CLASSIFICATION = 0x0014
    READ_CHANNEL_MAP = 0x0015
    READ_REMOTE_USED_FEATURES = 0x0016
    ENCRYPT = 0x0017
    RAND = 0x0018
    START_ENCRYPTION = 0x0019
    LONG_TERM_KEY_REQUEST_REPLY = 0x001A
    LONG_TERM_KEY_REQUEST_NEGATIVE_REPLY = 0x001B
    READ_SUPPORTED_STATES = 0x001C
    RECEIVER_TEST = 0x004F
    TRANSMITTER_TEST = 0x001E
    TEST_END = 0x001F
    REMOTE_CONNECTION_PARAMETER_REQUEST_REPLY = 0x0020
    REMOTE_CONNECTION_PARAMETER_REQUEST_NEGATIVE_REPLY = 0x0021
    SET_DATA_LENGTH = 0x0022
    #==============================================
    READ_SUGGESTED_DEFAULT_DATA_LENGTH = 0x0023
    WRITE_SUGGESTED_DEFAULT_DATA_LENGTH = 0x0024
    READ_LOCAL_P256_PUBLIC_KEY = 0x0025
    GENERATE_DHKEY = 0x0026
    ADD_DEVICE_TO_RESOLVING_LIST = 0x0027
    REMOVE_DEVICE_FROM_RESOLVING_LIST = 0x0028
    CLEAR_RESOLVING_LIST = 0x0029
    READ_RESOLVING_LIST_SIZE = 0x002A
    READ_PEER_RESOLVABLE_ADDRESS = 0x002B
    READ_LOCAL_RESOLVABLE_ADDRESS = 0x002C
    SET_ADDRESS_RESOLUTION_ENABLE = 0x002D
    SET_RESOLVABLE_PRIVATE_ADDRESS_TIMEOUT = 0x002E
    READ_MAXIMUM_DATA_LENGTH = 0x002F
    READ_PHY = 0x0030
    SET_DEFAULT_PHY = 0x0031
    SET_PHY = 0x0032
    # 0x0033–0x0034 reserved (“no longer used”)

    SET_ADVERTISING_SET_RANDOM_ADDRESS = 0x0035
    SET_EXTENDED_ADVERTISING_PARAMETERS = 0x0036
    SET_EXTENDED_ADVERTISING_DATA = 0x0037
    SET_EXTENDED_SCAN_RESPONSE_DATA = 0x0038
    SET_EXTENDED_ADVERTISING_ENABLE = 0x0039
    READ_MAXIMUM_ADVERTISING_DATA_LENGTH = 0x003A
    READ_NUMBER_OF_SUPPORTED_ADVERTISING_SETS = 0x003B
    REMOVE_ADVERTISING_SET = 0x003C
    CLEAR_ADVERTISING_SETS = 0x003D
    SET_PERIODIC_ADVERTISING_PARAMETERS = 0x003E
    SET_PERIODIC_ADVERTISING_DATA = 0x003F
    SET_PERIODIC_ADVERTISING_ENABLE = 0x0040
    SET_EXTENDED_SCAN_PARAMETERS = 0x0041
    SET_EXTENDED_SCAN_ENABLE = 0x0042
    EXTENDED_CREATE_CONNECTION = 0x0043
    
    #==========================================
    PERIODIC_ADV_CREATE_SYNC = 0x0044
    PERIODIC_ADV_CREATE_SYNC_CANCEL = 0x0045
    PERIODIC_ADV_TERMINATE_SYNC = 0x0046
    ADD_DEVICE_TO_PERIODIC_ADV_LIST = 0x0047
    REMOVE_DEVICE_FROM_PERIODIC_ADV_LIST = 0x0048
    CLEAR_PERIODIC_ADV_LIST = 0x0049
    READ_PERIODIC_ADV_LIST_SIZE = 0x004A
    READ_TRANSMIT_POWER = 0x004B
    READ_RF_PATH_COMPENSATION = 0x004C
    WRITE_RF_PATH_COMPENSATION = 0x004D
    SET_PRIVACY_MODE = 0x004E
    # 0x004F–0x0050 reserved

    SET_CONNLESS_CTE_TRANSMIT_PARAMS = 0x0051
    SET_CONNLESS_CTE_TRANSMIT_ENABLE = 0x0052
    SET_CONNLESS_IQ_SAMPLING_ENABLE = 0x0053
    SET_CONN_CTE_RECEIVE_PARAMS = 0x0054
    SET_CONN_CTE_TRANSMIT_PARAMS = 0x0055
    CONN_CTE_REQUEST_ENABLE = 0x0056
    CONN_CTE_RESPONSE_ENABLE = 0x0057
    READ_ANTENNA_INFORMATION = 0x0058
    SET_PERIODIC_ADV_RECEIVE_ENABLE = 0x0059
    PERIODIC_ADV_SYNC_TRANSFER = 0x005A
    SET_PERIODIC_ADV_SYNC_TRANSFER_PARAMS = 0x005B
    SET_DEFAULT_PERIODIC_ADV_SYNC_TRANSFER_PARAMS = 0x005C

    # 0x005D reserved
    MODIFY_SLEEP_CLOCK_ACCURACY = 0x005E
    # 0x005F reserved

    READ_ISO_TX_SYNC = 0x0060
    SET_CIG_PARAMS = 0x0061
    SET_CIG_PARAMS_TEST = 0x0062
    CREATE_CIS = 0x0063
    REMOVE_CIG = 0x0064
    ACCEPT_CIS_REQUEST = 0x0065
    REJECT_CIS_REQUEST = 0x0066
    CREATE_BIG = 0x0067
    CREATE_BIG_TEST = 0x0068
    TERMINATE_BIG = 0x0069
    BIG_CREATE_SYNC = 0x006A
    BIG_TERMINATE_SYNC = 0x006B
    REQUEST_PEER_SCA = 0x006C
    SETUP_ISO_DATA_PATH = 0x006D
    REMOVE_ISO_DATA_PATH = 0x006E
    ISO_TRANSMIT_TEST = 0x006F
    ISO_RECEIVE_TEST = 0x0070
    ISO_READ_TEST_COUNTERS = 0x0071
    ISO_TEST_END = 0x0072
    SET_HOST_FEATURE = 0x0073
    READ_ISO_LINK_QUALITY = 0x0074
    
    
    ENHANCED_READ_TRANSMIT_POWER_LEVEL = 0x0075
    READ_REMOTE_TRANSMIT_POWER_LEVEL = 0x0076
    SET_PATH_LOSS_REPORTING_PARAMS = 0x0077
    SET_PATH_LOSS_REPORTING_ENABLE = 0x0078
    SET_TRANSMIT_POWER_REPORTING_ENABLE = 0x0079
    SET_DATA_RELATED_ADDRESS_CHANGES = 0x007A
    SET_DEFAULT_SUBRATE = 0x007B
    SUBRATE_REQUEST = 0x007C
    SET_PERIODIC_ADV_SUBEVENT_DATA = 0x007D
    SET_PERIODIC_ADV_RESPONSE_DATA = 0x007E
    SET_PERIODIC_SYNC_SUBEVENT = 0x007F
    READ_ALL_LOCAL_SUPPORTED_FEATURES = 0x0080
    READ_ALL_REMOTE_FEATURES = 0x0081
    
    #===========================================
    CS_READ_LOCAL_SUPPORTED_CAPABILITIES = 0x0082
    CS_READ_REMOTE_SUPPORTED_CAPABILITIES = 0x0083
    CS_WRITE_CACHED_REMOTE_SUPPORTED_CAPABILITIES = 0x0086
    CS_SECURITY_ENABLE = 0x0087
    CS_SET_DEFAULT_SETTINGS = 0x0088
    CS_READ_REMOTE_FAE_TABLE = 0x0089
    CS_WRITE_CACHED_REMOTE_FAE_TABLE = 0x008A
    CS_CREATE_CONFIG = 0x008B
    CS_REMOVE_CONFIG = 0x008C
    CS_SET_CHANNEL_CLASSIFICATION = 0x008D
    CS_SET_PROCEDURE_PARAMETERS = 0x008E
    CS_PROCEDURE_ENABLE = 0x008F
    CS_TEST = 0x0090
    CS_TEST_END = 0x0091
    
    #===========================================
    SET_DECISION_DATA = 0x0092
    SET_DECISION_INSTRUCTIONS = 0x0093
    ADD_DEVICE_TO_MONITORED_ADVERTISERS_LIST = 0x0094
    REMOVE_DEVICE_FROM_MONITORED_ADVERTISERS_LIST = 0x0095
    CLEAR_MONITORED_ADVERTISERS_LIST = 0x0096
    ENABLE_MONITORING_ADVERTISERS = 0x0097
    READ_MONITORED_ADVERTISERS_LIST_SIZE = 0x0098
    FRAME_SPACE_UPDATE = 0x0099


# Vendor Specific Commands (OGF = 0x3F)
class VendorSpecificOCF(IntEnum):
    # Vendor specific opcodes can be defined here
    HCI_EXTENSION_SET_RX_GAIN = 0xFC00
    HCI_EXTENSION_SET_TX_POWER = 0xFC01
    HCI_EXTENSION_ONE_PACKET_PER_EVENT = 0xFC02
    HCI_EXTENSION_CLOCK_DIVIDE_ON_HALT = 0xFC03
    HCI_EXTENSION_DECLARE_NV_USAGE = 0xFC04
    HCI_EXTENSION_DECRYPT = 0xFC05
    HCI_EXTENSION_SET_LOCAL_SUPPORTED_FEATURES = 0xFC06
    HCI_EXTENSION_SET_FAST_TX_RESPONSE_TIME = 0xFC07
    HCI_EXTENSION_MODEM_TEST_TX = 0xFC08
    HCI_EXTENSION_MODEM_HOP_TEST_TX = 0xFC09
    HCI_EXTENSION_MODEM_TEST_RX = 0xFC0A
    HCI_EXTENSION_END_MODEM_TEST = 0xFC0B
    HCI_EXTENSION_SET_BDADDR = 0xFC0C
    HCI_EXTENSION_SET_SCA = 0xFC0D
    HCI_EXTENSION_ENABLE_PTM1 = 0xFC0E
    HCI_EXTENSION_SET_FREQUENCY_TUNING = 0xFC0F
    HCI_EXTENSION_SAVE_FREQUENCY_TUNING = 0xFC10
    HCI_EXTENSION_SET_MAX_DTM_TX_POWER = 0xFC11
    HCI_EXTENSION_MAP_PM_IO_PORT = 0xFC12
    HCI_EXTENSION_DISCONNECT_IMMEDIATE = 0xFC13
    HCI_EXTENSION_PACKET_ERROR_RATE = 0xFC14
    HCI_EXTENSION_PACKET_ERROR_RATE_BY_CHANNEL1 = 0xFC15
    HCI_EXTENSION_EXTEND_RF_RANGE = 0xFC16
    HCI_EXTENSION_ADVERTISER_EVENT_NOTICE = 0xFC17
    HCI_EXTENSION_CONNECTION_EVENT_NOTICE = 0xFC18
    HCI_EXTENSION_HALT_DURING_RF = 0xFC19
    HCI_EXTENSION_SET_SLAVE_LATENCY_OVERRIDE = 0xFC1A
    HCI_EXTENSION_BUILD_REVISION = 0xFC1B
    HCI_EXTENSION_DELAY_SLEEP = 0xFC1C
    HCI_EXTENSION_RESET_SYSTEM = 0xFC1D
    HCI_EXTENSION_OVERLAPPED_PROCESSING = 0xFC1E
    HCI_EXTENSION_NUMBER_COMPLETED_PACKETS_LIMIT = 0xFC1F
    HCI_EXTENSION_GET_CONNECTION_INFORMATION = 0xFC20
    HCI_EXTENSION_SET_MAX_DATA_LENGTH = 0xFC21
    HCI_EXTENSION_SCAN_EVENT_NOTICE = 0xFC22
    HCI_EXTENSION_SCAN_REQUEST_REPORT = 0xFC23

    L2CAP_DISCONNECTION_REQUEST = 0xFC86
    L2CAP_CONNECTION_PARAMETER_UPDATE_REQUEST = 0xFC92
    L2CAP_CONNECTION_REQUEST = 0xFC94
    L2CAP_CONNECTION_RESPONSE = 0xFC95
    L2CAP_FLOW_CONTROL_CREDIT = 0xFC96
    L2CAP_DATA = 0xFCF0
    L2CAP_REGISTER_PSM = 0xFCF1
    L2CAP_DEREGISTER_PSM = 0xFCF2
    L2CAP_PSM_INFO = 0xFCF3
    L2CAP_PSM_CHANNELS = 0xFCF4
    L2CAP_CHANNEL_INFO = 0xFCF5

    ATT_ERROR_RESPONSE = 0xFD01
    ATT_EXCHANGE_MTU_REQUEST = 0xFD02
    ATT_EXCHANGE_MTU_RESPONSE = 0xFD03
    ATT_FIND_INFORMATION_REQUEST = 0xFD04
    ATT_FIND_INFORMATION_RESPONSE = 0xFD05
    ATT_FIND_BY_TYPE_VALUE_REQUEST = 0xFD06
    ATT_FIND_BY_TYPE_VALUE_RESPONSE = 0xFD07
    ATT_READ_BY_TYPE_REQUEST = 0xFD08
    ATT_READ_BY_TYPE_RESPONSE = 0xFD09
    ATT_READ_REQUEST = 0xFD0A
    ATT_READ_RESPONSE = 0xFD0B
    ATT_READ_BLOB_REQUEST = 0xFD0C
    ATT_READ_BLOB_RESPONSE = 0xFD0D
    ATT_READ_MULTIPLE_REQUEST = 0xFD0E
    ATT_READ_MULTIPLE_RESPONSE = 0xFD0F
    ATT_READ_BY_GROUP_TYPE_REQUEST = 0xFD10
    ATT_READ_BY_GROUP_TYPE_RESPONSE = 0xFD11
    ATT_WRITE_REQUEST = 0xFD12
    ATT_WRITE_RESPONSE = 0xFD13
    ATT_PREPARE_WRITE_REQUEST = 0xFD16
    ATT_PREPARE_WRITE_RESPONSE = 0xFD17
    ATT_EXECUTE_WRITE_REQUEST = 0xFD18
    ATT_EXECUTE_WRITE_RESPONSE = 0xFD19
    ATT_HANDLE_VALUE_NOTIFICATION = 0xFD1B
    ATT_HANDLE_VALUE_INDICATION = 0xFD1D
    ATT_HANDLE_VALUE_CONFIRMATION = 0xFD1E

    GATT_DISC_ALL_CHAR_DESCS = 0xFD84
    GATT_DISCOVER_CHARACTERISTICS_BY_UUID = 0xFD88
    GATT_READ = 0xFD8A
    GATT_WRITE = 0xFD92
    GATT_WRITE_LONG = 0xFD96

    GAP_DEVICE_INITIALIZATION = 0xFE00
    GAP_CONFIGURE_DEVICE_ADDRESS = 0xFE03
    GAP_DEVICE_DISCOVERY_REQUEST = 0xFE04
    GAP_DEVICE_DISCOVERY_CANCEL = 0xFE05
    GAP_MAKE_DISCOVERABLE = 0xFE06
    GAP_UPDATE_ADVERTISING_DATA = 0xFE07
    GAP_END_DISCOVERABLE = 0xFE08
    GAP_ESTABLISH_LINK_REQUEST = 0xFE09
    GAP_TERMINATE_LINK_REQUEST = 0xFE0A
    GAP_AUTHENTICATE = 0xFE0B
    GAP_PASSKEY_UPDATE = 0xFE0C
    GAP_SLAVE_SECURITY_REQUEST = 0xFE0D
    GAP_SIGNABLE = 0xFE0E
    GAP_BOND = 0xFE0F
    GAP_TERMINATE_AUTH = 0xFE10
    GAP_UPDATE_LINK_PARAMETER_REQUEST = 0xFE11
    GAP_UPDATE_LINK_PARAMETER_REQUEST_REPLY = 0xFE12
    GAP_SET_PARAMETER = 0xFE30
    GAP_GET_PARAMETER = 0xFE31
    GAP_RESOLVE_PRIVATE_ADDRESS = 0xFE32
    GAP_SET_ADVERTISEMENT_TOKEN = 0xFE33
    GAP_REMOVE_ADVERTISEMENT_TOKEN = 0xFE34
    GAP_UPDATE_ADVERTISEMENT_TOKENS = 0xFE35
    GAP_BOND_SET_PARAMETER = 0xFE36
    GAP_BOND_GET_PARAMETER = 0xFE37

    UTIL_RESERVED = 0xFE80
    UTIL_NV_READ = 0xFE81
    UTIL_NV_WRITE = 0xFE82
    UTIL_FORCE_BOOT = 0xFE83
    UTIL_BUILD_REVISION = 0xFE84

    RESERVED = 0xFF00

    USER_PROFILES = 0xFF80



# Function to create complete opcode
def create_opcode(ogf, ocf):
    """Create HCI command opcode from OGF and OCF"""
    return ((ogf & 0x3F) << 10) | (ocf & 0x03FF)

# Dictionary of opcode to command name mappings
OPCODE_TO_NAME = {}

# Generate opcodes for all commands
def initialize_opcodes():
    # Link Control Commands
    for ocf in LinkControlOCF:
        opcode = create_opcode(OGF.LINK_CONTROL, ocf)
        OPCODE_TO_NAME[opcode] = f"LINK_CONTROL_{ocf.name}"
    
    # Link Policy Commands
    for ocf in LinkPolicyOCF:
        opcode = create_opcode(OGF.LINK_POLICY, ocf)
        OPCODE_TO_NAME[opcode] = f"LINK_POLICY_{ocf.name}"
    
    # Controller & Baseband Commands
    for ocf in ControllerBasebandOCF:
        opcode = create_opcode(OGF.CONTROLLER_BASEBAND, ocf)
        OPCODE_TO_NAME[opcode] = f"CONTROLLER_BASEBAND_{ocf.name}"
    
    # Information Parameters Commands
    for ocf in InformationOCF:
        opcode = create_opcode(OGF.INFORMATION_PARAMS, ocf)
        OPCODE_TO_NAME[opcode] = f"INFORMATION_{ocf.name}"
    
    # Status Parameters Commands
    for ocf in StatusOCF:
        opcode = create_opcode(OGF.STATUS_PARAMS, ocf)
        OPCODE_TO_NAME[opcode] = f"STATUS_{ocf.name}"
    
    # Testing Commands
    for ocf in TestingOCF:
        opcode = create_opcode(OGF.TESTING, ocf)
        OPCODE_TO_NAME[opcode] = f"TESTING_{ocf.name}"
    
    # LE Controller Commands
    for ocf in LEControllerOCF:
        opcode = create_opcode(OGF.LE_CONTROLLER, ocf)
        OPCODE_TO_NAME[opcode] = f"LE_{ocf.name}"
        
    # Vendor Specific Commands
    for ocf in VendorSpecificOCF:
        opcode = create_opcode(OGF.VENDOR_SPECIFIC, ocf)
        OPCODE_TO_NAME[opcode] = f"VENDOR_SPECIFIC_{ocf.name}"

# Initialize the opcode to name dictionary
initialize_opcodes()

# Common opcodes for easy reference
class HciOpcode:
    # LE Controller opcodes
    LE_SET_ADVERTISING_PARAMETERS = create_opcode(OGF.LE_CONTROLLER, LEControllerOCF.SET_ADVERTISING_PARAMETERS)
    LE_SET_ADVERTISING_DATA = create_opcode(OGF.LE_CONTROLLER, LEControllerOCF.SET_ADVERTISING_DATA)
    LE_SET_SCAN_PARAMETERS = create_opcode(OGF.LE_CONTROLLER, LEControllerOCF.SET_SCAN_PARAMETERS)
    LE_SET_SCAN_ENABLE = create_opcode(OGF.LE_CONTROLLER, LEControllerOCF.SET_SCAN_ENABLE)
    
    # Controller & Baseband opcodes
    RESET = create_opcode(OGF.CONTROLLER_BASEBAND, ControllerBasebandOCF.RESET)
    SET_EVENT_MASK = create_opcode(OGF.CONTROLLER_BASEBAND, ControllerBasebandOCF.SET_EVENT_MASK)
    
    # Link Control opcodes
    INQUIRY = create_opcode(OGF.LINK_CONTROL, LinkControlOCF.INQUIRY)
    DISCONNECT = create_opcode(OGF.LINK_CONTROL, LinkControlOCF.DISCONNECT)
    
    # Information Parameters opcodes
    READ_BD_ADDR = create_opcode(OGF.INFORMATION_PARAMS, InformationOCF.READ_BD_ADDR)
    READ_LOCAL_VERSION_INFORMATION = create_opcode(OGF.INFORMATION_PARAMS, InformationOCF.READ_LOCAL_VERSION_INFORMATION)